### ISSUE TITLE
Provide custom option to pass on for plan as well. 

### ISSUE THREAD

**Issue by azarudeena** [cds-snc/terraform-plan#127]
Similar to terraform init we can use Terraform plan as well for custom orgs. One of the use cases is to pass -lock=false or -lock-timeout etc..

**Comment by patheard** [comment]
Thanks for the suggestion - I'll look at adding an option to pass `-lock=false` into the Terraform commands.

**Comment by CalvinRodo** [comment]
As this is mainly being built for internal consumption we will not be adding a flag to bypass lock files as we don't want to internally encourage this behaviour, and we don't really have a tonne of capacity to add features we won't/don't use.

However if you would like to submit a PR we would be happy to review and potentially accept it into our code base.
