### ISSUE TITLE
[feature] Implement `skip-fmt` input

### ISSUE THREAD

**Issue by sturman** [cds-snc/terraform-plan#274]
Hi,

It'd be useful to have `skip-fmt` (similar to `skip-plan`) input. If it's `true` then `terraform fmt --check` is not execute so it does not check the code formatting and, as result, does not fail a workflow run.
Please see screenshot
![image](https://github.com/cds-snc/terraform-plan/assets/4456572/da803db0-ebfa-492f-adbe-4690715d86e0)

**Comment by patheard** [comment]
Alrighty, new `skip-fmt` option is now live in the `v3.1.0` and `v3` tags.  Hope it does the trick for you.
