### ISSUE TITLE
Duplicate PR comments even with comment-delete enabled

### ISSUE THREAD

**Issue by jessebye** [cds-snc/terraform-plan#311]
We've noticed that even with `comment-delete: true`, we still get duplicate PR comments for the same plans:

![Screenshot 2024-03-13 at 1 04 59 PM](https://github.com/cds-snc/terraform-plan/assets/8467862/c5b62890-ad60-47e9-b707-e6f71420592a)

In the logs, there is no mention of `Deleting comment` which we'd expect if that code path was being hit correctly. So either it isn't ever getting to the `deleteComment()` function, or the `comments.find()` comes back empty.

**Comment by jessebye** [comment]
Figured out the problem. Our GitHub token was not considered a "bot" user so the comments weren't identified correctly for deletion. By switching to the default `GITHUB_TOKEN` it was resolved.

**Comment by patheard** [comment]
Appreciate you digging into it - I've created #312 to track this since I think it's a valid use case that someone would use a personal access token tied to their account.
