### ISSUE TITLE
Formatting issue on failures

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/terraform-plan#33]
Seems like some colour codes are still making it through

From: https://github.com/cds-snc/covid-alert-metrics-terraform/pull/181

![image](https://user-images.githubusercontent.com/87738/125088555-891f1380-e09b-11eb-8802-0d9d4dc1d675.png)

**Comment by patheard** [comment]
Should be able to fix by adding `-no-color` args to the init and validate commands.

**Comment by patheard** [comment]
A secondary fix would be to also confirm that `results.fmt.output` only has files listed as right now it's adding extra error output to the PR comment.
