### ISSUE TITLE
Gateway validity check for OPA

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/terraform-plan#37]
In `aws_api_gateway_integration` you can specify a `type` (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_integration#type). TF plan does not validate the `uri` based on the type, (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_integration#uri

> Required if type is AWS, AWS_PROXY, HTTP or HTTP_PROXY. For HTTP integrations, the URI must be a fully formed, encoded HTTP(S) URL according to the RFC-3986 specification . For AWS integrations, the URI should be of the form arn:aws:apigateway:{region}:{subdomain.service|service}:{path|action}/{service_api}. region, subdomain and service are used to determine the right endpoint. e.g. arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:012345678901:function:my-func/invocations. For private integrations, the URI parameter is not used for routing requests to your endpoint, but is used for setting the Host header and for certificate validation.

It would be nice if the OPA could do that check :)

**Comment by CalvinRodo** [comment]
Handled by https://github.com/cds-snc/opa_checks/issues/13
